In [1]:
# import the library
%matplotlib inline

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# sklearn :: utils
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import KFold

# sklearn :: models
from sklearn.neighbors import KNeighborsClassifier

# sklearn :: evaluation metrics
from sklearn.metrics import cohen_kappa_score

sns.set_style('whitegrid')

# Problem definition

Predict when a pet will be adopted

# Load the data

In [2]:
df_train = pd.read_csv('train.csv')
df_test = pd.read_csv('test.csv')
print(df_train.shape, df_test.shape)

(10000, 24) (4993, 23)


# Feature Engineering

In [3]:
print(df_train.columns)
df_train.head()

Index(['Type', 'Name', 'Age', 'Breed1', 'Breed2', 'Gender', 'Color1', 'Color2',
       'Color3', 'MaturitySize', 'FurLength', 'Vaccinated', 'Dewormed',
       'Sterilized', 'Health', 'Quantity', 'Fee', 'State', 'RescuerID',
       'VideoAmt', 'Description', 'PetID', 'PhotoAmt', 'AdoptionSpeed'],
      dtype='object')


Type                                 Name  Age  Breed1  Breed2  Gender  \
0     1             ♥♥♥ Lily ♥♥♥   36     307       0       2   
1     2                               Cookie    3     266       0       1   
2     2  Favour Speedy Abundance And Courage    7     250     252       1   
3     1                                  NaN    3     307       0       1   
4     2                      Abandoned Kitty    1     266       0       1   

   Color1  Color2  Color3  MaturitySize      ...        Health  Quantity  Fee  \
0       2       7       0             2      ...             1         1    0   
1       6       7       0             2      ...             1         1    0   
2       1       2       0             2      ...             1         4    0   
3       2       0       0             3      ...             1         1    0   
4       1       6       7             1      ...             1         1    0   

   State                         RescuerID  VideoAmt  \
0  41326  337914b09c2fa5460e195197e994ef98         0   
1  41327  4bb1ebb92158078ad54a6bb23c10dffc         0   
2  41327  99ba8ce53b4d8515e417e7921563d923         0   
3  41327  3f3ef74c486beba3bc87f6dbaee772bf         0   
4  41401  844f03ab8054007d4be6686f3a9702b9         0   

                                         Description      PetID PhotoAmt  \
0  Adorable 3 year old Lily looking for a forever...  3f8824a3b      1.0   
1  i rescue this stary kitten from market near my...  9238eb7fc      1.0   
2  The mother was a Burmese cross and had since p...  f0a1f2b90      2.0   
3  This puppy is: 1. Male 2. 3 months old 3. Brow...  7d028bdea      4.0   
4  Mother cat gave birth to a litter of 3 and too...  8377bfe97      0.0   

   AdoptionSpeed  
0              4  
1              2  
2              4  
3              2  
4              2  

[5 rows x 24 columns]

In [4]:
# Check for missing values
df_train.isnull().sum(axis = 0)

Type               0
Name             842
Age                0
Breed1             0
Breed2             0
Gender             0
Color1             0
Color2             0
Color3             0
MaturitySize       0
FurLength          0
Vaccinated         0
Dewormed           0
Sterilized         0
Health             0
Quantity           0
Fee                0
State              0
RescuerID          0
VideoAmt           0
Description        8
PetID              0
PhotoAmt           0
AdoptionSpeed      0
dtype: int64

In [5]:
# apply dummies on the training set
col = 'Health'
df_dummies = pd.get_dummies(df_train[col])
df_dummies.columns = [str(col)+'_'+str(c) for c in df_dummies.columns]
df_train = pd.concat([df_train, df_dummies], axis=1)

# apply the same dummies on the test set
col = 'Health'
df_dummies = pd.get_dummies(df_test[col])
df_dummies.columns = [str(col)+'_'+str(c) for c in df_dummies.columns]
df_test = pd.concat([df_test, df_dummies], axis=1)

In [6]:
print(df_train.columns)

Index(['Type', 'Name', 'Age', 'Breed1', 'Breed2', 'Gender', 'Color1', 'Color2',
       'Color3', 'MaturitySize', 'FurLength', 'Vaccinated', 'Dewormed',
       'Sterilized', 'Health', 'Quantity', 'Fee', 'State', 'RescuerID',
       'VideoAmt', 'Description', 'PetID', 'PhotoAmt', 'AdoptionSpeed',
       'Health_1', 'Health_2', 'Health_3'],
      dtype='object')


In [7]:
# select the columns
X_columns = ['Age', 'Fee', 'Health_1', 'Health_2', 'Health_3']
y_column = ['AdoptionSpeed']

# Model Training

In [8]:
# split the data using sklearn

threshold = 0.8
X = df_train[X_columns]
y = df_train[y_column]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=1.0-threshold, shuffle=True)

print('X_train', X_train.shape)
print('y_train', y_train.shape)
print('X_test', X_test.shape)
print('y_test', y_test.shape)

X_train (8000, 5)
y_train (8000, 1)
X_test (2000, 5)
y_test (2000, 1)


In [9]:
# train a KNN Classifier
model = KNeighborsClassifier()
model.fit(X_train, y_train.values.ravel())
y_pred = model.predict(X_test)

# Model Evaluation

In [10]:
kappa = cohen_kappa_score(y_test, y_pred, weights ='quadratic')
print('kappa', round(kappa, 4))
print(confusion_matrix(y_test, y_pred))

kappa 0.1193
[[  1   9  19   5  14]
 [  3 105 149  84  60]
 [  2 147 212  93  97]
 [  0 109 153  78  97]
 [  3 103 174 117 166]]


Using Cross Validation

In [11]:
k = 10
results = []
kf = KFold(n_splits=k)
for train_index, test_index in kf.split(X):
    X_train, X_test = X.values[train_index], X.values[test_index]
    y_train, y_test = y.values[train_index], y.values[test_index]
    model.fit(X_train, y_train.ravel())
    y_pred = model.predict(X_test)
    kappa = cohen_kappa_score(y_test, y_pred, weights ='quadratic')
    results.append(round(kappa, 4))

print('Kappa for each fold:', results)
print('AVG(kappa)', round(np.mean(results), 4))
print('STD(kappa)', round(np.std(results), 4))

Kappa for each fold: [0.0529, 0.0387, 0.1073, 0.1097, 0.1246, 0.0607, 0.0404, 0.0566, 0.0834, 0.0286]
AVG(kappa) 0.0703
STD(kappa) 0.032


# Prepare your submission

In [12]:
df_prediction = df_test[X_columns]
df_test['AdoptionSpeed'] = model.predict(df_prediction)
df_test[['PetID', 'AdoptionSpeed']]

PetID  AdoptionSpeed
0     f42161740              3
1     0118db3a8              4
2     e5164d828              3
3     5335bfb38              4
4     ff2cf88a0              4
5     1d13441b9              3
6     7d835cf7c              0
7     577d15fea              1
8     91736f444              3
9     db194aec8              3
10    10516f3c6              3
11    c3106dcd5              3
12    fc3fbbb99              4
13    42dd3f3ff              4
14    da3be5cb2              4
15    4e9a13862              3
16    2fbf2cb7c              2
17    f45457bdc              1
18    aad08c47b              0
19    181d40c5e              3
20    1a3c44785              3
21    6786609aa              4
22    1c67c5f4c              3
23    bf6a56d33              3
24    06fda20a2              4
25    b940cf8b8              3
26    239c4b696              1
27    b67a29908              3
28    72f092b4b              3
29    7d1d7a4f6              3
...         ...            ...
4963  ed0185e39              1
4964  bf90589d1              4
4965  0f796d3f9              3
4966  6d53b2d19              2
4967  7bc54baef              3
4968  87615b2c6              4
4969  6f07e7abf              3
4970  3bf6cdab0              1
4971  00ac364a4              2
4972  578b82f50              3
4973  f24991ef7              1
4974  2e9a64836              1
4975  3dab3050c              1
4976  4f6029457              4
4977  b23e29c89              4
4978  0c46298f8              0
4979  2f6cde44b              4
4980  2f3677597              4
4981  256f40704              4
4982  653f94080              1
4983  878e36da4              0
4984  46cf6356e              3
4985  ef50eab33              3
4986  a40116bf1              1
4987  7ed14130d              1
4988  3b2b69d20              4
4989  360215e23              1
4990  0c612e8df              4
4991  9b1241ef0              3
4992  ffe7f0b70              4

[4993 rows x 2 columns]

In [13]:
df_test[['PetID', 'AdoptionSpeed']].to_csv('submission_knn.csv', index=False)